import { useEffect, useMemo, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import {
  ArrowDownToLine, ArrowRight, BookOpen, Check, Clock3, FileText,
  FolderOpen, GraduationCap, HardDriveUpload, LibraryBig, LoaderCircle,
  LockKeyhole, Menu, MessageSquareText, Plus, RefreshCw, Search, Send,
  Share2, ShieldCheck, Sparkles, Trash2, Upload, X,
} from 'lucide-react';
import { Link } from 'wouter';
import {
  getListSharedNotesQueryKey, useAskNoteQuestion, useDeleteNote, useDownloadNote, useGetDashboard,
  useHealthCheck, useListMyNotes, useListSharedNotes, useSetNoteSharing,
  useUploadNote,
} from '@workspace/api-client-react';
import type { AnswerResult, Dashboard, Note, NoteSubject } from '@workspace/api-client-react';
import { getBrowserProfileId } from '@/lib/profile';

const ownerId = getBrowserProfileId();
const sharedQueryKey = getListSharedNotesQueryKey();
const subjects: NoteSubject[] = ['DSA', 'DBMS', 'OS', 'CN'];
const subjectNames: Record<NoteSubject, string> = { DSA: 'Data Structures', DBMS: 'Database Systems', OS: 'Operating Systems', CN: 'Computer Networks' };
const bytes = (n: number) => n < 1048576 ? `${Math.max(1, Math.round(n / 1024))} KB` : `${(n / 1048576).toFixed(1)} MB`;
const date = (d: string) => new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(new Date(d));

export function Brand({ inverted = false }: { inverted?: boolean }) {
  return <Link href="/" data-testid="link-brand" className={`inline-flex items-center gap-2.5 font-extrabold tracking-[-.04em] ${inverted ? 'text-white' : 'text-[#183b5b]'}`}><span className={`grid h-9 w-9 place-items-center rounded-xl ${inverted ? 'bg-[#80c7df] text-[#143651]' : 'bg-[#183b5b] text-white'}`}><BookOpen size={18} /></span><span className="text-[18px]">Campus<span className={inverted ? 'text-[#8ed2e5]' : 'text-[#2c829b]'}>Sathi</span></span></Link>;
}

export function Home() {
  return <main className="min-h-[100dvh] overflow-hidden bg-[#f7fafc] text-[#193750]">
    <header className="mx-auto flex max-w-[1200px] items-center justify-between px-5 py-5 sm:px-8"><Brand /><nav className="hidden items-center gap-8 text-[13px] font-semibold text-[#597083] md:flex"><a href="#how">How it works</a><a href="#why">Built for students</a><a href="#project">Project details</a></nav><Link href="/dashboard" className="rounded-lg bg-[#173e60] px-4 py-2.5 text-[13px] font-bold text-white hover:bg-[#245777]" data-testid="link-open-workspace">Open workspace <ArrowRight className="ml-1 inline" size={15} /></Link></header>
    <section className="mx-auto grid max-w-[1200px] items-center gap-12 px-5 pb-20 pt-12 sm:px-8 md:grid-cols-[1.08fr_.92fr] md:pb-28 md:pt-20">
      <div className="relative z-10 page-enter"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#cde0e8] bg-white px-3.5 py-2 text-[11px] font-bold uppercase tracking-[.12em] text-[#34728a]"><span className="h-2 w-2 rounded-full bg-[#4a9c9e]" />A study workspace for B.Tech CSE</div><h1 className="max-w-[700px] font-[var(--app-font-serif)] text-[clamp(2.8rem,6vw,5.4rem)] font-extrabold leading-[1.04] tracking-[-.065em] text-[#173b5a]">Make your lecture notes work <span className="text-[#367d91]">for you.</span></h1><p className="mt-6 max-w-[560px] text-[17px] leading-8 text-[#5b7182]">Turn the PDFs you already have into focused revision notes, ask questions against your own material, and pass useful knowledge forward.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/dashboard" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#173e60] px-6 py-4 text-sm font-bold text-white shadow-[0_8px_18px_rgba(23,62,96,.16)] hover:bg-[#245777]" data-testid="link-upload-notes">Upload Your Notes Now <ArrowRight size={17} /></Link><a href="#how" className="inline-flex items-center justify-center rounded-xl border border-[#cbdce4] bg-white px-6 py-4 text-sm font-bold text-[#33576f]">See how it works</a></div><div className="mt-8 flex items-center gap-3 text-xs font-medium text-[#6a7e8e]"><ShieldCheck size={17} className="text-[#4c8892]" />Your questions are answered from your notes, not the open web.</div></div>
      <div className="relative mx-auto w-full max-w-[480px] page-enter [animation-delay:120ms]"><div className="absolute -right-8 -top-10 h-44 w-44 rounded-full bg-[#dceef2] blur-2xl" /><div className="relative rounded-[28px] border border-[#d7e5ea] bg-[#eaf3f6] p-4 shadow-[0_25px_60px_rgba(27,65,92,.12)] sm:p-6"><div className="paper-grid relative min-h-[370px] overflow-hidden rounded-[19px] border border-[#d8e5e9] bg-[#fbfdfe] p-5 sm:p-7"><div className="flex items-center justify-between border-b border-[#deeaee] pb-4"><span className="flex items-center gap-2 text-xs font-bold text-[#3c6278]"><FileText size={16} />lecture_07_graphs.pdf</span><span className="rounded-full bg-[#edf6f6] px-2.5 py-1 font-mono text-[9px] text-[#4f878a]">DSA / 12 PAGES</span></div><div className="mt-7 rounded-xl border border-[#dce8ec] bg-white/90 p-5 shadow-sm"><div className="font-mono text-[9px] uppercase tracking-[.15em] text-[#67909e]">Quick revision · generated from your PDF</div><h2 className="mt-3 font-[var(--app-font-serif)] text-[24px] font-extrabold text-[#1d425f]">Graph Traversal</h2><div className="mt-5 space-y-3.5">{['BFS explores vertices level by level using a queue.', 'DFS follows each branch before backtracking.', 'Both traversals run in O(V + E) with adjacency lists.'].map((t, i) => <div key={t} className="flex gap-3 text-[12px] leading-5 text-[#536b7b]"><span className="grid h-4 w-4 shrink-0 place-items-center rounded-full bg-[#e8f2f5] text-[9px] font-bold text-[#36758a]">{i + 1}</span>{t}</div>)}</div><div className="mt-5 rounded-lg bg-[#f0f6f7] p-3 font-mono text-[10px] text-[#3b6876]">Time complexity&nbsp;&nbsp; O(V + E)</div></div><div className="absolute bottom-5 right-4 flex items-center gap-2 rounded-xl border border-[#d4e3e7] bg-white px-3 py-2.5 text-[11px] font-semibold text-[#476579] shadow-md"><MessageSquareText size={15} className="text-[#3c8291]" />Ask: When should I use BFS?</div></div></div><div className="absolute -bottom-5 -left-3 flex items-center gap-2 rounded-xl border border-[#d8e6ea] bg-white px-4 py-3 text-[11px] font-bold text-[#3d697e] shadow-lg sm:-left-7"><LockKeyhole size={15} />Answers grounded in your PDFs</div></div>
    </section>
    <section className="border-y border-[#e1eaee] bg-white"><div className="mx-auto grid max-w-[1200px] gap-7 px-5 py-9 sm:px-8 md:grid-cols-[1fr_auto] md:items-center"><p className="max-w-[760px] font-[var(--app-font-serif)] text-[clamp(1.5rem,3vw,2.15rem)] font-extrabold leading-tight tracking-[-.045em] text-[#214663]">70% students fail to revise because notes are unorganized</p><span className="text-xs font-semibold text-[#6c8190]">A better system starts with what you already own.</span></div></section>
    <section id="how" className="mx-auto max-w-[1200px] px-5 py-20 sm:px-8 md:py-24"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="font-mono text-[10px] uppercase tracking-[.19em] text-[#3b8294]">Simple by design</span><h2 className="mt-3 max-w-[590px] font-[var(--app-font-serif)] text-3xl font-extrabold tracking-[-.05em] text-[#1d425f] sm:text-4xl">One useful loop for every lecture.</h2></div><p className="max-w-[360px] text-sm leading-6 text-[#667d8c]">No new study system to learn. Bring your notes, find the important parts, and keep moving.</p></div><div className="rounded-[24px] border border-[#d9e6ea] bg-[#eef5f7] p-6 sm:p-10"><div className="mb-8 text-center font-[var(--app-font-serif)] text-[clamp(1.1rem,3.5vw,2rem)] font-extrabold tracking-[-.04em] text-[#1d4b68]">Upload → Summarize → Ask Doubt → Share</div><div className="grid gap-3 md:grid-cols-4">{[{ icon: Upload, title: 'Bring a lecture PDF', text: 'Keep your course material in one dependable workspace.' }, { icon: Sparkles, title: 'Get the essentials', text: 'A local keyword-based summary pulls together revision points.' }, { icon: MessageSquareText, title: 'Ask your notes', text: 'Find the paragraph that best matches your question.' }, { icon: Share2, title: 'Pass it along', text: 'Share useful material in the subject hub for juniors.' }].map(({ icon: Icon, title, text }, i) => <article key={title} className="rounded-2xl border border-[#dce7ea] bg-white p-5"><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-[#84a1ad]">0{i + 1} / 04</span><Icon size={18} className="text-[#3d8191]" /></div><h3 className="mt-7 text-[15px] font-bold text-[#264a64]">{title}</h3><p className="mt-2 text-xs leading-5 text-[#6a7f8c]">{text}</p></article>)}</div></div></section>
    <section id="why" className="bg-[#173e60] text-white"><div className="mx-auto grid max-w-[1200px] gap-12 px-5 py-16 sm:px-8 md:grid-cols-[.9fr_1.1fr] md:items-center md:py-20"><div><span className="font-mono text-[10px] uppercase tracking-[.2em] text-[#8bc9d9]">A practical study companion</span><h2 className="mt-4 font-[var(--app-font-serif)] text-4xl font-extrabold leading-[1.08] tracking-[-.055em] sm:text-5xl">Less hunting.<br />More understanding.</h2><p className="mt-5 max-w-[440px] text-sm leading-7 text-[#d0dfe6]">CampusSathi helps you get back to the thinking part of studying. Summaries and answers are generated locally from the material you upload, with no external AI service.</p></div><div className="grid gap-3 sm:grid-cols-2">{[{ icon: Clock3, title: 'Save 3 Hours Daily', text: 'Spend less time reorganizing lecture files.' }, { icon: BookOpen, title: 'Stay with your source', text: 'Review summaries tied directly to your PDF.' }, { icon: ShieldCheck, title: 'Know how it works', text: 'Keyword logic is clearly labeled, never disguised as AI.' }, { icon: GraduationCap, title: 'Help the next batch', text: 'Share subject notes in one place for juniors.' }].map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-white/15 bg-white/[.06] p-5"><Icon size={19} className="text-[#91d0de]" /><h3 className="mt-4 text-sm font-bold">{title}</h3><p className="mt-2 text-xs leading-5 text-[#c0d3dd]">{text}</p></div>)}</div></div></section>
    <section id="project" className="mx-auto flex max-w-[1200px] flex-col gap-6 px-5 py-16 sm:px-8 md:flex-row md:items-center md:justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-[#528596]">Built for the classroom</div><h2 className="mt-3 font-[var(--app-font-serif)] text-2xl font-extrabold tracking-[-.04em] text-[#1d425f]">A focused B.Tech CSE project.</h2><p className="mt-2 text-sm text-[#718390]">A compact workflow for organizing course PDFs into revision-ready material.</p></div><Link href="/dashboard" className="inline-flex w-fit items-center gap-2 rounded-xl bg-[#173e60] px-5 py-3.5 text-sm font-bold text-white" data-testid="link-home-cta">Upload Your Notes Now <ArrowRight size={16} /></Link></section>
    <footer className="border-t border-[#dfe8eb] bg-[#f0f5f6]"><div className="mx-auto flex max-w-[1200px] flex-col gap-5 px-5 py-7 sm:px-8 md:flex-row md:items-center md:justify-between"><div><div className="text-sm font-bold text-[#31556c]">Project Objective for B.Tech Minor Project</div><div className="mt-1 text-xs text-[#718491]">A student-owned workspace for lecture notes and peer sharing.</div></div><div className="text-xs text-[#718491]"><b className="text-[#4f6979]">Stack</b>&nbsp;&nbsp;HTML, Tailwind CSS, JS; Python Flask; PyMuPDF</div></div></footer>
  </main>;
}

function Stat({ label, value, suffix, icon: Icon }: { label: string; value: string | number; suffix?: string; icon: typeof FileText }) { return <div className="rounded-2xl border border-[#dce6ea] bg-white p-4 sm:p-5"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-[#6c7e8c]">{label}</span><Icon size={17} className="text-[#468397]" /></div><div className="mt-3 font-[var(--app-font-serif)] text-2xl font-extrabold tracking-[-.04em] text-[#1c4562]">{value}<span className="ml-1 text-[11px] font-semibold tracking-normal text-[#82929c]">{suffix}</span></div></div>; }

function Summary({ note }: { note: Note }) {
  return <div className="mt-4 space-y-5"><div><div className="mb-2 font-mono text-[9px] uppercase tracking-[.15em] text-[#748c98]">Topic</div><p className="text-sm font-semibold text-[#264a64]">{note.summary.topic || 'Summary topic not available'}</p></div>{note.summary.bullets?.length > 0 && <div><div className="mb-2 font-mono text-[9px] uppercase tracking-[.15em] text-[#748c98]">Key points</div><ul className="space-y-2">{note.summary.bullets.map((b, i) => <li key={`${i}-${b}`} className="flex gap-2.5 text-[13px] leading-5 text-[#536b7b]"><span className="mt-[7px] h-1.5 w-1.5 rounded-full bg-[#4e91a0]" />{b}</li>)}</ul></div>}{!!note.summary.definitions?.length && <div><div className="mb-2 font-mono text-[9px] uppercase tracking-[.15em] text-[#748c98]">Definitions</div><ul className="space-y-2">{note.summary.definitions.map((b, i) => <li key={`${i}-${b}`} className="rounded-lg bg-[#f1f6f7] px-3 py-2 text-[12px] leading-5 text-[#50697a]">{b}</li>)}</ul></div>}{!!note.summary.formulas?.length && <div><div className="mb-2 font-mono text-[9px] uppercase tracking-[.15em] text-[#748c98]">Formulas</div><div className="flex flex-wrap gap-2">{note.summary.formulas.map((b, i) => <code key={`${i}-${b}`} className="rounded-md bg-[#edf4f6] px-2.5 py-1.5 font-mono text-[11px] text-[#356d7c]">{b}</code>)}</div></div>}<div className="border-t border-[#e6edef] pt-3 text-[10px] text-[#87969e]">Source text: {note.summary.sourceWordCount.toLocaleString()} words · Local keyword-based summary</div></div>;
}

function NoteItem({ note, active, onSelect, onShare, onDelete, onDownload, busy }: { note: Note; active: boolean; onSelect: () => void; onShare: () => void; onDelete: () => void; onDownload: () => void; busy: boolean }) {
  return <article className={`rounded-xl border p-3.5 transition ${active ? 'border-[#8cb6c3] bg-[#f0f7f8]' : 'border-[#e3ebee] bg-white hover:border-[#c2d8df]'}`} data-testid={`card-note-${note.id}`}><div className="flex items-start gap-3"><button onClick={onSelect} className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-[#edf4f6] text-[#39798c]" aria-label={`Open ${note.title}`} data-testid={`button-select-note-${note.id}`}><FileText size={18} /></button><button onClick={onSelect} className="min-w-0 flex-1 text-left" data-testid={`button-note-title-${note.id}`}><div className="truncate text-[13px] font-bold text-[#2b4e65]">{note.title}</div><div className="mt-1 truncate text-[10px] text-[#81919b]">{note.filename} · {bytes(note.fileSize)}</div></button><span className="rounded-md bg-[#eef4f5] px-2 py-1 font-mono text-[9px] text-[#557788]">{note.subject}</span></div><div className="mt-3 flex items-center justify-between border-t border-[#e8eef0] pt-2.5"><span className="text-[10px] text-[#82919a]">{date(note.uploadedAt)} · {note.isShared ? 'Shared' : 'Private'}</span><div className="flex items-center gap-1"><button onClick={onDownload} disabled={busy} title="Download PDF" className="rounded-md p-1.5 text-[#6e8290] hover:bg-[#e9f1f3] disabled:opacity-50" data-testid={`button-download-note-${note.id}`}><ArrowDownToLine size={14} /></button><button onClick={onShare} disabled={busy} title={note.isShared ? 'Stop sharing' : 'Share note'} className={`rounded-md p-1.5 hover:bg-[#e9f1f3] disabled:opacity-50 ${note.isShared ? 'text-[#3b8290]' : 'text-[#6e8290]'}`} data-testid={`button-share-note-${note.id}`}><Share2 size={14} /></button><button onClick={onDelete} disabled={busy} title="Delete note" className="rounded-md p-1.5 text-[#a46b6b] hover:bg-[#fbefef] disabled:opacity-50" data-testid={`button-delete-note-${note.id}`}><Trash2 size={14} /></button></div></div></article>;
}

export function DashboardPage() {
  // This selected note scopes both the summary and doubt search to one PDF.
  const [notes, setNotes] = useState<Note[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [subject, setSubject] = useState<NoteSubject>('DSA');
  const [title, setTitle] = useState('');
  const [file, setFile] = useState<File | null>(null);
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState<AnswerResult | null>(null);
  const [hubSubject, setHubSubject] = useState<'All' | NoteSubject>('All');
  const [search, setSearch] = useState('');
  const [mobileNav, setMobileNav] = useState(false);
  const [notice, setNotice] = useState('');
  const [uploadError, setUploadError] = useState('');
  const [stats, setStats] = useState<Dashboard | null>(null);
  const queryClient = useQueryClient();
  const health = useHealthCheck();
  const shared = useListSharedNotes();
  const dashboard = useGetDashboard();
  const myNotes = useListMyNotes();
  const upload = useUploadNote();
  const sharing = useSetNoteSharing();
  const askMutation = useAskNoteQuestion();
  const deletion = useDeleteNote();
  const downloadMutation = useDownloadNote();
  const selected = notes.find((n) => n.id === selectedId) ?? notes[0] ?? null;
  // The local profile ID keeps separate browser workspaces distinct without account setup.
  const reloadNotes = () => myNotes.mutate({ data: { ownerId } }, { onSuccess: (data) => { setNotes(data); setSelectedId((id) => data.some((n) => n.id === id) ? id : data[0]?.id ?? null); } });
  const reloadStats = () => dashboard.mutate({ data: { ownerId } }, { onSuccess: setStats });
  useEffect(() => { reloadNotes(); reloadStats(); }, []);
  useEffect(() => { if (upload.isSuccess || sharing.isSuccess || deletion.isSuccess) queryClient.invalidateQueries({ queryKey: sharedQueryKey }); }, [upload.isSuccess, sharing.isSuccess, deletion.isSuccess, queryClient]);
  const visibleShared = useMemo(() => (shared.data ?? []).filter((n) => (hubSubject === 'All' || n.subject === hubSubject) && `${n.title} ${n.filename} ${n.subject}`.toLowerCase().includes(search.toLowerCase())), [shared.data, hubSubject, search]);
  // FormData lets Flask receive the original PDF file without base64 conversion.
  const submitUpload = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!file || !title.trim()) { setUploadError('Add a title and choose a PDF to continue.'); return; }
    if (file.type !== 'application/pdf' && !file.name.toLowerCase().endsWith('.pdf')) { setUploadError('Please choose a PDF file.'); return; }
    setUploadError('');
    upload.mutate({ data: { ownerId, title: title.trim(), subject, file } }, { onSuccess: (note) => { setNotes((items) => [note, ...items.filter((n) => n.id !== note.id)]); setSelectedId(note.id); setTitle(''); setFile(null); setNotice('PDF added. Your local summary is ready.'); reloadStats(); const input = document.getElementById('pdf-file') as HTMLInputElement | null; if (input) input.value = ''; }, onError: () => setUploadError('The PDF could not be uploaded. Check that the API server is running and try again.') });
  };
  const toggleShare = (note: Note) => sharing.mutate({ data: { ownerId, noteId: note.id, isShared: !note.isShared } }, { onSuccess: (updated) => { setNotes((items) => items.map((n) => n.id === updated.id ? updated : n)); setNotice(updated.isShared ? 'Note shared with the subject hub.' : 'Note is private again.'); reloadStats(); }, onError: () => setNotice('Sharing could not be updated. Please retry.') });
  const remove = (note: Note) => { if (!window.confirm(`Delete “${note.title}” from your workspace?`)) return; deletion.mutate({ data: { ownerId, noteId: note.id } }, { onSuccess: () => { setNotes((items) => items.filter((n) => n.id !== note.id)); setSelectedId((id) => id === note.id ? null : id); setNotice('Note deleted from your workspace.'); reloadStats(); }, onError: () => setNotice('This note could not be deleted. Please retry.') }); };
  const download = (note: Note) => downloadMutation.mutate({ data: { ownerId, noteId: note.id } }, { onSuccess: (blob) => { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = note.filename; a.click(); URL.revokeObjectURL(url); }, onError: () => setNotice('The PDF could not be downloaded.') });
  // Flask searches only the selected note and returns a source paragraph, not generated facts.
  const ask = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); if (!selected || !question.trim()) return; askMutation.mutate({ data: { ownerId, noteId: selected.id, question: question.trim() } }, { onSuccess: setAnswer, onError: () => setAnswer({ answer: 'Could not search this note right now. Please try again.', found: false, matchedKeywords: [] }) }); };
  const refresh = () => { reloadNotes(); reloadStats(); queryClient.invalidateQueries({ queryKey: sharedQueryKey }); };
  const busy = sharing.isPending || deletion.isPending || downloadMutation.isPending;

  return <div className="min-h-[100dvh] bg-[#f5f8fa] text-[#203d52]">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[248px] flex-col bg-[#173e60] px-4 py-5 text-white transition-transform md:translate-x-0 ${mobileNav ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between px-2"><Brand inverted /><button onClick={() => setMobileNav(false)} className="rounded p-1 text-white md:hidden" aria-label="Close navigation" data-testid="button-close-mobile-nav"><X size={18} /></button></div><div className="mt-10 px-3 font-mono text-[9px] uppercase tracking-[.17em] text-[#8da9b7]">Workspace</div><nav className="mt-3 space-y-1"><a href="#overview" className="flex items-center gap-3 rounded-xl bg-white/10 px-3 py-3 text-[13px] font-semibold"><LibraryBig size={17} className="text-[#98d3df]" />My study desk</a><a href="#my-notes" className="flex items-center gap-3 rounded-xl px-3 py-3 text-[13px] text-[#d2e0e7] hover:bg-white/[.08]"><FolderOpen size={17} />My notes</a><a href="#share-hub" className="flex items-center gap-3 rounded-xl px-3 py-3 text-[13px] text-[#d2e0e7] hover:bg-white/[.08]"><Share2 size={17} />Share Hub</a></nav><div className="mt-auto rounded-2xl border border-white/10 bg-white/[.06] p-4"><div className="flex items-center gap-2 text-[11px] font-bold"><span className={`h-2 w-2 rounded-full ${health.isError ? 'bg-[#e4a28b]' : 'bg-[#83cbb1]'}`} />{health.isLoading ? 'Checking local service' : health.isError ? 'Service unavailable' : 'Study service ready'}</div><p className="mt-2 text-[10px] leading-4 text-[#b4c8d2]">Summaries and answers use local keyword matching, not external AI.</p></div><div className="mt-4 flex items-center gap-3 border-t border-white/10 px-2 pt-4"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#83c3d2] text-[11px] font-bold text-[#183c56]">CS</div><div><div className="text-xs font-semibold">CSE student</div><div className="mt-0.5 text-[9px] text-[#9db5c1]">Browser-local profile</div></div></div></aside>
    {mobileNav && <button className="fixed inset-0 z-30 bg-[#102a3d]/40 md:hidden" aria-label="Close menu overlay" onClick={() => setMobileNav(false)} data-testid="button-nav-overlay" />}
    <div className="min-h-[100dvh] md:pl-[248px]"><header className="sticky top-0 z-20 flex h-[68px] items-center justify-between border-b border-[#e1e9ec] bg-[#f8fafb]/95 px-4 backdrop-blur sm:px-7"><div className="flex items-center gap-3"><button onClick={() => setMobileNav(true)} className="rounded-lg p-2 text-[#49697e] hover:bg-[#eaf1f3] md:hidden" aria-label="Open navigation" data-testid="button-open-mobile-nav"><Menu size={19} /></button><div className="hidden text-xs text-[#85939b] sm:block">CampusSathi <span className="px-1.5">/</span> <b className="text-[#34566d]">Study desk</b></div><div className="text-xs font-semibold text-[#34566d] sm:hidden">Study desk</div></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 rounded-full border border-[#dfe8eb] bg-white px-3 py-2 text-[10px] text-[#67808e] sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-[#59a794]" />Local keyword tools</div><button onClick={refresh} className="flex items-center gap-2 rounded-lg border border-[#dbe5e8] bg-white px-3 py-2 text-[11px] font-semibold text-[#527083] hover:bg-[#f1f6f7]" data-testid="button-refresh-workspace"><RefreshCw size={14} />Refresh</button></div></header>
    <main className="mx-auto max-w-[1500px] px-4 py-6 sm:px-7 sm:py-8 page-enter">
      <section id="overview" className="mb-7 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[#56899a]">Your learning, in order</div><h1 className="mt-2 font-[var(--app-font-serif)] text-[30px] font-extrabold tracking-[-.055em] text-[#1d425f] sm:text-[36px]">Good to see you, student.</h1><p className="mt-2 max-w-[550px] text-sm leading-6 text-[#71828d]">Bring your lecture PDFs here. Your own notes become the source for every summary and answer.</p></div><div className="flex items-center gap-2 rounded-xl border border-[#dce8eb] bg-white px-3.5 py-2.5 text-[10px] leading-4 text-[#69808e]"><ShieldCheck size={16} className="text-[#4b8e91]" /><span>Uploaded notes appear in Share Hub.<br /><b className="text-[#456779]">You can make a note private.</b></span></div></section>
      {notice && <div role="status" data-testid="status-workspace-notice" className="mb-4 flex items-center justify-between rounded-xl border border-[#c9e0df] bg-[#edf7f5] px-4 py-3 text-xs text-[#3a6e6b]"><span className="flex items-center gap-2"><Check size={15} />{notice}</span><button onClick={() => setNotice('')} className="p-1" aria-label="Dismiss notice" data-testid="button-dismiss-notice"><X size={14} /></button></div>}
      <section className="mb-7 grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Notes in workspace" value={stats?.totalNotes ?? (notes.length || '—')} icon={FileText} /><Stat label="Shared with classmates" value={stats?.sharedNotes ?? '—'} icon={Share2} /><Stat label="Words organized" value={stats ? stats.totalWords.toLocaleString() : '—'} icon={BookOpen} /><Stat label="Time back" value={stats?.hoursSaved ?? '—'} suffix="hrs" icon={Clock3} /></section>
      <div className="grid items-start gap-5 xl:grid-cols-[minmax(360px,.88fr)_minmax(460px,1.12fr)]">
        <div className="space-y-5">
          <section className="rounded-2xl border border-[#dce6ea] bg-white p-5 study-shadow sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[13px] font-bold text-[#264a64]"><HardDriveUpload size={17} className="text-[#418396]" />Add lecture PDF</div><p className="mt-1.5 text-[11px] text-[#82919a]">The summary is extracted from your uploaded PDF.</p></div><span className="rounded-full bg-[#eef5f6] px-2.5 py-1 font-mono text-[9px] text-[#5b7c88]">PDF ONLY</span></div><form onSubmit={submitUpload} className="mt-5 space-y-3.5"><label className="block"><span className="mb-1.5 block text-[10px] font-bold text-[#5b7180]">Note title</span><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Graph Traversal — Lecture 07" className="h-10 w-full rounded-lg border border-[#dce5e8] bg-[#fbfcfd] px-3 text-xs outline-none placeholder:text-[#a1adb4] focus:border-[#78aab8]" data-testid="input-note-title" /></label><label className="block"><span className="mb-1.5 block text-[10px] font-bold text-[#5b7180]">Subject</span><select value={subject} onChange={(e) => setSubject(e.target.value as NoteSubject)} className="h-10 w-full rounded-lg border border-[#dce5e8] bg-[#fbfcfd] px-3 text-xs outline-none focus:border-[#78aab8]" data-testid="select-upload-subject">{subjects.map((s) => <option key={s} value={s}>{s} · {subjectNames[s]}</option>)}</select></label><label htmlFor="pdf-file" className="flex min-h-[92px] cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[#b9d1d9] bg-[#f7fafb] px-3 py-4 text-center hover:border-[#6e9fad] hover:bg-[#f0f7f8]"><Upload size={18} className="text-[#4f8a9b]" /><span className="mt-2 text-[11px] font-semibold text-[#4b6879]">{file ? file.name : 'Choose a PDF from your device'}</span><span className="mt-1 text-[9px] text-[#8b9aa2]">{file ? bytes(file.size) : 'Select a file to create a revision summary'}</span><input id="pdf-file" type="file" accept="application/pdf,.pdf" className="sr-only" onChange={(e) => setFile(e.target.files?.[0] ?? null)} data-testid="input-pdf-file" /></label>{uploadError && <p className="text-[11px] text-[#ad5858]" role="alert" data-testid="status-upload-error">{uploadError}</p>}<button type="submit" disabled={upload.isPending} className="flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-[#1c4c6d] text-xs font-bold text-white hover:bg-[#286783] disabled:opacity-60" data-testid="button-upload-note">{upload.isPending ? <><LoaderCircle className="animate-spin" size={15} />Building your summary…</> : <><Plus size={15} />Upload and summarize</>}</button><p className="text-center text-[9px] text-[#89979f]">Local keyword-based summary · no external AI key or service</p></form></section>
          <section id="my-notes" className="rounded-2xl border border-[#dce6ea] bg-white p-5 study-shadow sm:p-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-[13px] font-bold text-[#264a64]">My notes</h2><p className="mt-1 text-[10px] text-[#82919a]">{notes.length} {notes.length === 1 ? 'PDF' : 'PDFs'} in this browser profile</p></div><FolderOpen size={17} className="text-[#4b8492]" /></div>{myNotes.isPending && !notes.length ? <div className="space-y-2.5"><div className="h-[80px] animate-pulse rounded-xl bg-[#edf2f4]" /><div className="h-[80px] animate-pulse rounded-xl bg-[#edf2f4]" /></div> : myNotes.isError && !notes.length ? <div className="rounded-xl bg-[#f8f3ef] p-4 text-xs text-[#806d5e]">Could not load your notes.<button onClick={reloadNotes} className="ml-2 font-bold underline" data-testid="button-retry-notes">Try again</button></div> : notes.length === 0 ? <div className="rounded-xl border border-dashed border-[#d5e2e6] bg-[#f9fbfc] px-4 py-8 text-center"><FileText size={20} className="mx-auto text-[#558896]" /><p className="mt-3 text-xs font-bold text-[#4a6576]">Your study shelf is clear.</p><p className="mt-1 text-[10px] text-[#82919a]">Upload a lecture PDF to start revising.</p></div> : <div className="max-h-[390px] space-y-2.5 overflow-y-auto">{notes.map((note) => <NoteItem key={note.id} note={note} active={selected?.id === note.id} busy={busy} onSelect={() => { setSelectedId(note.id); setAnswer(null); }} onShare={() => toggleShare(note)} onDelete={() => remove(note)} onDownload={() => download(note)} />)}</div>}</section>
        </div>
        <div className="space-y-5">
          <section className="rounded-2xl border border-[#dce6ea] bg-white p-5 study-shadow sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[13px] font-bold text-[#264a64]"><Sparkles size={17} className="text-[#4b8995]" />Revision summary</div><p className="mt-1.5 text-[11px] text-[#82919a]">A quick pass through the ideas in your source PDF.</p></div><span className="rounded-full border border-[#dbe8e9] bg-[#f5faf9] px-2.5 py-1 text-[9px] font-semibold text-[#55847e]">KEYWORD-BASED</span></div>{selected ? <><div className="mt-5 flex items-center gap-3 rounded-xl bg-[#f2f7f8] p-3.5"><FileText size={18} className="text-[#3b7c8d]" /><div className="min-w-0"><div className="truncate text-xs font-bold text-[#35566b]">{selected.title}</div><div className="mt-1 text-[10px] text-[#83939b]">{selected.subject} · {selected.summary.sourceWordCount.toLocaleString()} source words</div></div></div><Summary note={selected} /></> : <div className="mt-5 flex min-h-[230px] flex-col items-center justify-center rounded-xl border border-dashed border-[#d5e2e6] bg-[#f9fbfc] px-6 text-center"><BookOpen size={20} className="text-[#558896]" /><p className="mt-3 text-xs font-bold text-[#4a6576]">A focused recap, ready when you are.</p><p className="mt-1 max-w-[270px] text-[10px] leading-5 text-[#83919a]">Upload a PDF or choose one from My notes to see its generated summary here.</p></div>}</section>
          <section className="rounded-2xl border border-[#dce6ea] bg-white p-5 study-shadow sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[13px] font-bold text-[#264a64]"><MessageSquareText size={17} className="text-[#4b8995]" />Ask your notes</div><p className="mt-1.5 text-[11px] text-[#82919a]">Search for the most relevant paragraph in your own material.</p></div><span className="rounded-full bg-[#f1f5f6] px-2.5 py-1 text-[9px] text-[#738893]">NOTE-ONLY</span></div>{!selected ? <div className="mt-5 rounded-xl bg-[#f6f9fa] p-4 text-[11px] text-[#7b8e99]">Choose or upload one of your notes before asking a question.</div> : <form onSubmit={ask} className="mt-4"><label htmlFor="question" className="mb-1.5 block text-[10px] font-bold text-[#5b7180]">Question for <span className="text-[#3d7c8c]">{selected.title}</span></label><div className="flex gap-2"><input id="question" value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="What is the time complexity of BFS?" className="h-10 min-w-0 flex-1 rounded-lg border border-[#dce5e8] bg-[#fbfcfd] px-3 text-xs outline-none placeholder:text-[#a1adb4] focus:border-[#78aab8]" data-testid="input-note-question" /><button disabled={!question.trim() || askMutation.isPending} className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-[#1c4c6d] text-white disabled:opacity-50" aria-label="Ask question" data-testid="button-ask-question">{askMutation.isPending ? <LoaderCircle className="animate-spin" size={16} /> : <Send size={15} />}</button></div>{answer && <div className={`mt-4 rounded-xl border p-4 ${answer.found ? 'border-[#d4e4e5] bg-[#f4f9f8]' : 'border-[#e9e2d9] bg-[#fbf8f4]'}`} data-testid="result-note-answer"><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-bold text-[#456b78]">{answer.found ? 'Best matching passage' : 'No strong match found'}</span><span className="font-mono text-[8px] uppercase tracking-wider text-[#83939a]">Local keyword result</span></div><p className="mt-2 text-[12px] leading-5 text-[#536b78]">{answer.answer}</p>{answer.matchedKeywords.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{answer.matchedKeywords.map((k) => <span key={k} className="rounded-full bg-white px-2 py-1 text-[9px] text-[#547988]">{k}</span>)}</div>}</div>}<p className="mt-2 text-[9px] text-[#89979f]">Answers match keywords to paragraphs in this note. No outside knowledge is used.</p></form>}</section>
        </div>
      </div>
      <section id="share-hub" className="mt-7 rounded-2xl border border-[#dce6ea] bg-white p-5 study-shadow sm:p-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2 text-[13px] font-bold text-[#264a64]"><Share2 size={17} className="text-[#4b8995]" />Share Hub</div><p className="mt-1.5 text-[11px] text-[#82919a]">Uploaded course notes appear here for classmates. Filter by subject and download what helps.</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8b9aa3]" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search shared notes" className="h-9 w-full rounded-lg border border-[#dce5e8] bg-[#fbfcfd] pl-9 pr-3 text-[11px] outline-none sm:w-[190px]" data-testid="input-search-shared-notes" /></label><div className="flex flex-wrap gap-1.5" role="group" aria-label="Filter shared notes by subject">{(['All', ...subjects] as const).map((s) => <button key={s} onClick={() => setHubSubject(s)} className={`rounded-lg px-3 py-2 text-[10px] font-bold ${hubSubject === s ? 'bg-[#1c4c6d] text-white' : 'bg-[#f0f5f6] text-[#64808f]'}`} data-testid={`button-filter-${s.toLowerCase()}`}>{s}</button>)}</div></div></div>
        {shared.isLoading ? <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[1, 2, 3].map((n) => <div key={n} className="h-[116px] animate-pulse rounded-xl bg-[#edf2f4]" />)}</div> : shared.isError ? <div className="mt-5 rounded-xl bg-[#f8f3ef] p-5 text-xs text-[#806d5e]" data-testid="status-share-hub-error">The Share Hub is not available right now. <button onClick={() => queryClient.invalidateQueries({ queryKey: sharedQueryKey })} className="ml-1 font-bold underline" data-testid="button-retry-share-hub">Retry</button></div> : visibleShared.length === 0 ? <div className="mt-5 rounded-xl border border-dashed border-[#d5e2e6] bg-[#f9fbfc] px-5 py-8 text-center" data-testid="status-share-hub-empty"><Share2 size={18} className="mx-auto text-[#558896]" /><p className="mt-3 text-xs font-bold text-[#4a6576]">{search || hubSubject !== 'All' ? 'No shared notes match this view.' : 'The shared shelf is waiting for its first note.'}</p><p className="mt-1 text-[10px] text-[#82919a]">{search || hubSubject !== 'All' ? 'Try another subject or search term.' : 'Share one of your notes above to help a classmate revise.'}</p></div> : <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visibleShared.map((note) => <article key={note.id} className="rounded-xl border border-[#e0e9eb] bg-[#fcfdfd] p-4 hover:border-[#b9d4dc]" data-testid={`card-shared-note-${note.id}`}><div className="flex items-start justify-between gap-2"><div className="flex min-w-0 items-center gap-2.5"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#edf4f6] text-[#3f7c8d]"><FileText size={16} /></div><div className="min-w-0"><div className="truncate text-xs font-bold text-[#35566b]">{note.title}</div><div className="mt-1 truncate text-[9px] text-[#82919a]">{subjectNames[note.subject]}</div></div></div><span className="rounded-md bg-[#eef4f5] px-2 py-1 font-mono text-[9px] text-[#557788]">{note.subject}</span></div><div className="mt-3 flex items-center justify-between border-t border-[#e8eef0] pt-3"><span className="text-[9px] text-[#8a989f]">{bytes(note.fileSize)} · Shared {date(note.uploadedAt)}</span><button onClick={() => download(note)} disabled={downloadMutation.isPending} className="inline-flex items-center gap-1.5 rounded-lg bg-[#eaf2f4] px-2.5 py-2 text-[10px] font-bold text-[#35667a] disabled:opacity-50" data-testid={`button-download-shared-${note.id}`}><ArrowDownToLine size={13} />Download</button></div></article>)}</div>}
      </section>
      <footer className="mt-7 flex flex-col gap-2 border-t border-[#e1e9ec] py-5 text-[9px] text-[#89979f] sm:flex-row sm:justify-between"><span>CampusSathi · A student workspace for B.Tech CSE</span><span>HTML, Tailwind CSS, JS; Python Flask; PyMuPDF</span></footer>
    </main></div>
  </div>;
}
